### PR TITLE
Fixes #30 Update typedi dependency

### LINKED ISSUE #30: Update typedi dependency
Please update `typedi` peer dependency to `^0.8.0` (currently `"typedi": "^0.7.2"`).

### PR DESCRIPTION
**Pull request by XBeg9**
Please see #30 issue

### CODE REVIEW

**Comment by XBeg9** [comment]
any updates?

**Comment by XBeg9** [comment]
@RodolfoSilva Please check #30, peer dependency has been merged already in another PR. We just need to release npm package.

**Comment by RodolfoSilva** [comment]
@XBeg9 thanks 😛

**Comment by XBeg9** [comment]
@RodolfoSilva could you please do that? :)

**Comment by RodolfoSilva** [comment]
@XBeg9 No, I'm not a maintainer, I believe only @pleerock can do.

**Comment by pleerock** [comment]
published in `typeorm-typedi-extensions@0.2.3`

**Pull request closed without merging**
