### PR TITLE
feat: support for scoped containers

### PR DESCRIPTION
**Pull request by ashleyw**
As raised by @mailaneel in https://github.com/typeorm/typeorm-typedi-extensions/issues/35

### CODE REVIEW

**Comment by constb** [comment]
I only see three lines actually changed is this PR. I'd prefer if code style changes were made separately…

**Comment by ashleyw** [comment]
Oops! Thought I'd disabled prettier. Will amend later today 👍🏼

**Comment by ashleyw** [comment]
@constb fixed 👍

**Comment by ashleyw** [comment]
@constb Hi, could we get this reviewed and merged please so we don't have to rely on our own fork. Thanks! 😊

**Comment by constb** [comment]
um, I'm not a maintainer of this package :)

@pleerock ? @19majkel94 ?

**Comment by seawatts** [comment]
Can we get this merged in? @MichalLytek @ashleyw ??

**Comment by MichalLytek** [comment]
@seawatts I have no power here 😞

**Comment by Oiimate** [comment]
@pleerock Would really appreciate a merge ;)

**Comment by NoNameProvided** [comment]
Added in 3f13dc7f0bd9fa58c04499760257371dad32292d.

**Pull request closed without merging**
