### PR TITLE
Decorators renaming

### PR DESCRIPTION
**Pull request by 19majkel94**
Closing #23.

### CODE REVIEW

**Comment by pleerock** [comment]
We shall probably left other decorators as well with `@deprecated` tag, just delegate calls to inject decorators, it has zero cost for us.

**Comment by 19majkel94** [comment]
@pleerock I've added aliases for backward compatibility. The new release still has to be a major due to peer dependencies update.

**Comment by 19majkel94** [comment]
ping @pleerock, pls merge asap 😉

**Comment by pleerock** [comment]
Thanks @19majkel94 and sorry 😆

**Pull request merged**
